name: Stream_Line_Sender_Part

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Test_Framework.sln
      Test_Project_Path: Test_Framework.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

 
    - name: Run tests and collect coverage
      run: dotnet test .\Test_Framework.sln --collect:"XPlat Code Coverage"

    - name: Install coverage report generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Make coverage report
      run: reportgenerator "-reports:Test_Framework\TestResults\*\*.xml" "-targetdir:coverage"
    
    - name: Create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage
        retention-days: 21
